TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 4
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True

MODEL:
  NUM_CLASSES: 3          # 🔥改这里：三类分类输出
  ARCH: vitb16
  MODEL_NAME: TemporalClipVideo
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  TEMPORAL_MODELING_TYPE: expand_temporal_view
  KEEP_RAW_MODEL: True
  RAW_MODEL_DISTILLATION: True
  DISTILLATION_RATIO: 2.0

TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 3

SOLVER:
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 3.33e-6
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 3.33e-8
  WARMUP_START_LR: 3.33e-8
  WARMUP_EPOCHS: 2.0
  LR_POLICY: cosine
  MAX_EPOCH: 12
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.01
  OPTIMIZING_METHOD: adamw
