ROOT=/root/FROSTER
CKPT=/root/autodl-tmp/CKPT

# RGB / IR 视频根路径
RGB_PREFIX=/root/autodl-tmp/motion
IR_PREFIX=/root/autodl-tmp/motion

# train/val/test CSV 路径
RGB_ANN=/root/autodl-tmp/motion/annotations-rgb
IR_ANN=/root/autodl-tmp/motion/annotations-ir

# label map（确保名称一致）
LABEL_MAP=$RGB_ANN/label_map.json

export CUDA_VISIBLE_DEVICES=0

TRAIN_FILE=train.csv
VAL_FILE=val.csv
TEST_FILE=test.csv
TRAIN_FILE_IR=$TRAIN_FILE
VAL_FILE_IR=$VAL_FILE
TEST_FILE_IR=$TEST_FILE

cd $ROOT

python -W ignore -u tools/run_net.py \
  --cfg configs/Kinetics/TemporalCLIP_vitb16_8x16_STAdapter_UCF101_rgb_ir.yaml \
  --opts DATA.PATH_TO_DATA_DIR $RGB_ANN \
  DATA.PATH_TO_DATA_DIR_IR $IR_ANN \
  DATA.PATH_PREFIX $RGB_PREFIX \
  DATA.PATH_PREFIX_IR $IR_PREFIX \
  DATA.MATCH_DUAL_MODAL_BY_ORDER True \
  TRAIN_FILE $TRAIN_FILE \
  VAL_FILE $VAL_FILE \
  TEST_FILE $TEST_FILE \
  TRAIN_FILE_IR $TRAIN_FILE_IR \
  VAL_FILE_IR $VAL_FILE_IR \
  TEST_FILE_IR $TEST_FILE_IR \
  DATA.PATH_LABEL_SEPARATOR "," \
  DATA.INDEX_LABEL_MAPPING_FILE $LABEL_MAP \
  DATA.MODALITY rgb_ir \
  DATA.INPUT_CHANNEL_NUM [3,1] \
  DATA.MEAN_IR [0.5] \
  DATA.STD_IR [0.226] \
  DATA.NUM_FRAMES 16 \
  DATA.NUM_FRAMES_IR 8 \
  TRAIN.ENABLE True \
  OUTPUT_DIR $CKPT/basetraining/motion_rgb_ir \
  TRAIN.BATCH_SIZE 1 \
  TEST.BATCH_SIZE 8 \
  TEST.NUM_ENSEMBLE_VIEWS 3 \
  TEST.NUM_SPATIAL_CROPS 1 \
  NUM_GPUS 1 \
  SOLVER.MAX_EPOCH 12 \
  SOLVER.WARMUP_EPOCHS 5.0 \
  SOLVER.BASE_LR 3.33e-6 \
  SOLVER.WARMUP_START_LR 3.33e-8 \
  SOLVER.COSINE_END_LR 3.33e-8 \
  TRAIN.MIXED_PRECISION True \
  DATA.DECODING_BACKEND "pyav" \
  MODEL.NUM_CLASSES 3 \
  TRAIN.EVAL_PERIOD 5 \
  TRAIN.CHECKPOINT_PERIOD 99999 \
  MODEL.LOSS_FUNC soft_cross_entropy \
  TRAIN.LINEAR_CONNECT_CLIMB False \
  TRAIN.CLIP_ORI_PATH /root/.cache/clip/ViT-B-16.pt \
  TRAIN.LINEAR_CONNECT_LOSS_RATIO 0.0 \
  MODEL.RAW_MODEL_DISTILLATION True \
  MODEL.KEEP_RAW_MODEL True \
  MODEL.DISTILLATION_RATIO 2.0
